DROP TABLE IF EXISTS BUSINFORMATION;

CREATE TABLE BUSINFORMATION
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    BUSNUMBER     VARCHAR(10) NOT NULL,
    DIRECTIONCODE VARCHAR(1)  NOT NULL,
    BUSSTOPNUMBER VARCHAR(10) NOT NULL
);